# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SimpleTO-DOList' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SimpleTO-DOList
  pod 'FontAwesomeIconFactory'
  pod 'Firebase/Auth'
  pod 'Firebase/Crash'
  pod 'MagicalRecord'
  pod 'RestKit'
  pod 'RestKit/Testing'

  target 'SimpleTO-DOListTests' do
    inherit! :search_paths
    # Pods for testing
	pod 'OCMock'
  end

end
